### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by panovvitalik** [Ra-Na/GTranslate-strings-xml#14]
12 =========================
<string name="app_log"><a href="">Send</a></string>
    Traceback (most recent call last):
  File "gtranslate.py", line 280, in <module>
    root[i][element].tail = " " + translate(root[i][element].tail, OUTPUTLANGUAGE, INPUTLANGUAGE).replace('\\ ', '\\').replace('\\ n ', '\\n').replace('\\n ', '\\n').replace('/ ', '/')
  File "gtranslate.py", line 210, in translate
    r = requests.get("https://translate.google.com/m?hl=%s&sl=%s&q=%s"% (to_language, language, to_translate.replace(" ", "+")))
AttributeError: 'NoneType' object has no attribute 'replace'
Exit status : 1

**Comment by Ra-Na** [comment]
Could you provide the strings.xml file that raised this error?

**Comment by panovvitalik** [comment]
> Could you provide the strings.xml file that raised this error?
<resources>
    <string name="app_log"><a href="">Send</a></string>
</resources>

**Comment by Ra-Na** [comment]
The "None"-case was not covered. On the webpage it works now, I update the repo later.
