### ISSUE TITLE
Translate to more than one language at the same time?

### ISSUE THREAD

**Issue by CDrosos** [Ra-Na/GTranslate-strings-xml#15]
It could be great if we could translate to many languages with one click, and to also save those translated files with the correct structure (values-language/strings.xml)

Also it would be REALLY nice if we have an option to not download them but to copy/ paste the result, this would be really helpful when you already have some translations and you want to add some new strings to them and you don't want to translate and download the whole files again.

**Comment by Ra-Na** [comment]
Feel free to fork the repo and add features. I have unfortunately not much time for this, I will just maintain the core functionality.
