### ISSUE TITLE
'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by chiccoss** [Ra-Na/GTranslate-strings-xml#18]
Hi,

When trying to call he google script it gives the null NoneType error.

Traceback (most recent call last):
  File "C:\Users\git\GTranslate-strings-xml\GoogleTranslate\gtranslate.py", line 280, in <module>
    INPUTLANGUAGE).replace('\\ ', '\\').replace('\\ n ',
  File "C:\Users\git\GTranslate-strings-xml\GoogleTranslate\gtranslate.py", line 178, in translate
    if to_translate.replace(" ", "+"):
**AttributeError: 'NoneType' object has no attribute 'replace'**

the problem i here 👍 
           to_translate.replace(" ", "+")

I've tried to change this part of code :

    if to_translate.replace(" ", "+") is Null:
        print("this is null")

    else:
        r = requests.get(
            "https://translate.google.com/m?hl=%s&sl=%s&q=%s" % (to_language, language, to_translate.replace(" ", "+")))

but i dont know what to do if it is null

**Comment by tiger1289** [comment]
Is this issue is resolved, I am also getting the same error

**Comment by LeoK987** [comment]
Sounds similar to my new issue #25.  Found a way to work around it.
