### ISSUE TITLE
translation for <item> inside <string-array> in strings.xml file

### ISSUE THREAD

**Issue by Deeptimay** [Ra-Na/GTranslate-strings-xml#2]
Hi R-Na, this py script is very helpful. Though it has only one drawback, it cannot translate <item> inside the <strings-array>. I'm not familiar with python. So could you please add this functionality to the project.

Thanks in adv.

Example:
<string-array name="blogs_title">         
       <item>What can I look for in the Blog section?</item>
        <item>Do I need to be signed in to view blogs?</item>
        <item>Who contributes to Blogs?</item>
        <item>Can I contribute to by writing articles?</item>
        <item>Can I reach out to the article contributors directly?</item>
        <item>How does an article or blog become a featured article?</item>
    </string-array>

**Comment by Ra-Na** [comment]
Can you be more explicit about the missing functionality? I do not understand inside what you want to translate. 

Regards, 

Rana

**Comment by Deeptimay** [comment]
`    <string name="radio_others">Search in Others</string>
    <string name="btn_search">Search</string>
    <string name="radio_design_ideas">Search in Design Ideas</string>

    <string-array name="search_title">
        <item>What can I search for?</item>
        <item>Do I have to have an account to search and view information?</item>
        <item>How do I search for products shown in a design?</item>
    </string-array>`

**Comment by Deeptimay** [comment]
`    <string name="radio_others">Search in Others</string>
    <string name="btn_search">Search</string>
    <string name="radio_design_ideas">Search in Design Ideas</string>

  \
    <string-array name="search_title">
        <item>What can I search for?</item>
        <item>Do I have to have an account to search and view information?</item>
        <item>How do I search for products shown in a design?</item>
    </string-array>`

**Comment by Deeptimay** [comment]
`    <string name="radio_others">Search in Others</string>
    <string name="btn_search">Search</string>
    <string name="radio_design_ideas">Search in Design Ideas</string>

    
    <string-array name="search_title">
        <item>What can I search for?</item>
        <item>Do I have to have an account to search and view information?</item>
        <item>How do I search for products shown in a design?</item>
    </string-array>`

**Comment by Deeptimay** [comment]
` <string name="btn_search">Search</string>
    <string name="radio_design_ideas">Search in Design Ideas</string>
    <string-array name="search_title">
        <item>What can I search for?</item>
        <item>Do I have to have an account to search and view information?</item>
        <item>How do I search for products shown in a design?</item>
    </string-array>`

**Comment by Deeptimay** [comment]
` <string name="btn_search">Search</string>
    <string name="radio_design_ideas">Search in Design Ideas</string>

    <string-array name="search_title">
        <item>What can I search for?</item>
        <item>Do I have to have an account to search and view information?</item>
        <item>How do I search for products shown in a design?</item>
    </string-array>`

**Comment by Deeptimay** [comment]
` <string name="btn_search">Search</string>
    <string name="radio_design_ideas">Search in Design Ideas</string>
    <string-array name="search_title">
        <item>What can I search for?</item>
        <item>Do I have to have an account to search and view information?</item>
        <item>How do I search for products shown in a design?</item>
    </string-array>`

In the above code this <string>s are automatically translated but <item> s inside <string-array> are left as it is

**Comment by Ra-Na** [comment]
Do I understand you correctly that only the strings in <item> </item> tags are translated, but you want also the strings between the <string name="..."> and </string> tags to translate?

**Comment by Deeptimay** [comment]
Actually it is exactly the opposite. 

`<string name=''...''></string>`
is working fine.

But
`<string-array name="search_title"> <item>What can I search for?</item>
</string-array> `
is not working

**Comment by Ra-Na** [comment]
OK I will look into it. I see the issue now.

**Comment by Ra-Na** [comment]
OK it should work now. I tested it with the file `teststrings.xml`. Thanks for your input.

**Comment by Deeptimay** [comment]
Thanks, it helped a lot. :+1:  :)
