### ISSUE TITLE
Python scrips have stopped working!

### ISSUE THREAD

**Issue by mobilevisuals** [Ra-Na/GTranslate-strings-xml#20]
I used your python scrips for translation , but they don't work anymore. I tried on Wednesday and then got a correct translation. Something happened on Thursday, which made your scrips no longer working. They can not translate anymore, they but lots of trash HTML code in the translated files. I attach the translated file and as you can see, it is full with trash HTML. Here is the URL to this file:

http://mobile-visuals.com/1590237496_de.xml

I will donate some $ to your project if you fix this issue!

**Comment by Ra-Na** [comment]
It stopped working because Google Translate has put up a captcha. "Our systems have detected unusual traffic from your computer network.  This page checks to see if it's really you sending the requests, and not a robot."
You can use the copy-paste variant or download the gtranslate.py file from the repository (https://github.com/Ra-Na/GTranslate-strings-xml/blob/master/GoogleTranslate/gtranslate.py) and run `PYTHONIOENCODING=utf8 python3 gtranslate.py fr en frstrings.xml` where fr is the inlanguage, en the outlanguage and `ftstrings.xml` the string file

**Comment by mobilevisuals** [comment]
Thanks for the quick answer! What do you mean with copy-paste variant? Is that something I can use with your Python scripts? What do I need to run the gtranslate.py file? 

I have a long experience in Java and Android, but have never programmed any Python. Do I need a web server to run the gtranslate.py file? I think that Google should have allowed this traffic from your server. Google Translate has got much better recently. I think that it is now good enough to use for localization for non-text centered apps, like my Visualizer-apps. Google Translate was not at all as good a few years ago. Then I would not wanted to use it for localization.

**Comment by Ra-Na** [comment]
On the website there are two options: goggle translate and copy-paste. If you use the copy paste variant the strings are extracted, you copy-paste them to a translation engine of your choice in one block and then use the web page to parse them back to your xml file.
For using the python script you need a phyton 3 installation, but you don't have to code anything. Just run the mentioned command on a terminal after downloading gtranslate.py

**Comment by mobilevisuals** [comment]
The copy & paste option does not seem to work like it should. The line numbers are included in the translation and all line breaks are written as \\ n \\ . I pasted an example of how it looks like. Am I doing something wrong or is there a bug in the copy&paste functionality?
251 </string>
    <string name="purchase_settings">Upgrade auf Vollversion!
    <string name="helppaid">*** Musikauswahl *** \\ n \\ n Berühren Sie den Bildschirm, während ein Visualizer abgespielt wird, um die Benutzeroberfläche anzuzeigen. Spielen Sie Musik mit einem beliebigen Player wie Winamp oder Spotify. Dann wechseln Sie zu dieser App. Anschließend wird die Musik visualisiert. Über das Radiosymbol stehen 47 Funkkanäle zur Verfügung. Ein Player für Ihre Musikdateien ist ebenfalls enthalten. Verwenden Sie die Tasten, um Wiedergabe / Pause, vorherigen / nächsten Titel auszuwählen. \\ n \\ n *** Einstellungen *** \\ n \\ nÜber 100 Einstellungen sind verfügbar. Passen Sie die Visualisierungen nach Ihrem Geschmack an. Ändern Sie ihr Aussehen, damit sie wie Ihre eigenen Kreationen aussehen. Baue deine eigenen Sternensysteme und Tunnel. \\ n \\ n *** Interaktivität *** \\ n \\ nSie können Ihre Fahrt durch die 3D-Welten und Tunnel mit dem interaktiven Gyroskop steuern. Ändern Sie die Geschwindigkeit mit den Tasten + und -. \\ n \\ n *** Visueller Stimulationsmodus *** \\ n \\ nDrücken Sie die Pause, um die Musik anzuhalten. Sie können die App dann als visuelles Simulationswerkzeug ohne Musik verwenden. Die Visualisierung hat dann unterschiedliche Muster, daher lohnt es sich, dies zu versuchen! \\ n
253 </string>

**Comment by mobilevisuals** [comment]
I tried to run the Python file, but did not get longer than "this is not recognized as an internal command" eventhough I installed Pythen 3.8 and have it among my environment variables. But Google Translate has a limit of 5000 characters and my file is bigger than that, so I assume it would not work anyway.

**Comment by Ra-Na** [comment]
I don't know how environment variables like pythonioencoding are set in windows. Simply try without setting it, maybe it's set to utf8 by default.

**Comment by Ra-Na** [comment]
Hello again. Google has apparently taken the site of the blacklist, so it works again. Is it possible that you have a really large strings.xml that caused the blacklisting in the first place? I would appreciate it if you use the Copy-Paste variant or run the python program yourself. Please tell me wether you managed to run gtranslate.py on your command prompt.
