### ISSUE TITLE
I can't work now, I can work normally before

### ISSUE THREAD

**Issue by hjh2881** [Ra-Na/GTranslate-strings-xml#21]
![微信截图_20200526165503](https://user-images.githubusercontent.com/15795338/82880969-ab2a0500-9f71-11ea-9d69-0c2747f711c3.png)

**Comment by hjh2881** [comment]
can't work now, can work normally before

**Comment by Ra-Na** [comment]
Read this line:

** Our systems have detected unusual traffic from your computer network. **

That means that google considers the ASRT-requests SPAM and puit up a Captcha. Your options:

a) Wait that the websites is not blacklistet anymore 
b) download the gtranslate.py from the repository and run it from your PC 
c) or use the COPY-PASTE-Variant.
