### ISSUE TITLE
Parsing to xml keeps the line numbers

### ISSUE THREAD

**Issue by psydj1** [Ra-Na/GTranslate-strings-xml#23]
I'm now using the translate and copy paste method. So the issue is when I copy my translation back to the textfield and press submit. 
The xml file that I download has line numbers before the <string/> tags.

example below

`    "<string name=""important">Attenzione! 

4  "\</string>"`

**Comment by Ra-Na** [comment]
I can not reproduce this issue. Please provide the text you are pasting. It must be formatted exactlty like the extracted text block, like so if "::" is your delimiter:

1::Translation of the first string
2::Translation of the second string

etc

**Comment by psydj1** [comment]
Thank you for a quick reply. 

Below is My original string.xml (english)

1::Can cause apps to not work correctly. To prevent it, select and protect our app in your battery settings.
2::Protect from battery saving
3::Attention!
4::New users only!
5::Thank you for trying our app!
6::50% faster. All features. No ads
7::Please exclude our app from being stopped by your system

Below is Translated by Google Translate to Lithuanian

1 :: gali sukelti programų netinkamą veikimą. Norėdami to išvengti, pasirinkite ir apsaugokite mūsų programą akumuliatoriaus nustatymuose.
2: Apsaugokite nuo akumuliatoriaus taupymo
3 :: Dėmesio!
4 :: Tik nauji vartotojai!
5 :: Ačiū, kad išbandėte mūsų programą!
6 :: 50% greičiau. Visos savybės. Nėra skelbimų

Below is When I download the new xml string
(the line numbers are still there, and also noticed that the texts don't match the right keys)
Maybe it's the special characters?

<string name="can_cause_apps_to_not_work_correctly_nto_prevent_it_select_and_protect_our_app_in_your_battery_settings">gali sukelti programų netinkamą veikimą. Norėdami to išvengti, pasirinkite ir apsaugokite mūsų programą akumuliatoriaus nustatymuose.
2: Apsaugokite nuo akumuliatoriaus taupymo
3 </string>
    <string name="protect_from_battery_saving">Dėmesio!
4 </string>
    <string name="important">Tik nauji vartotojai!
5 </string>
    <string name="new_users_only">Ačiū, kad išbandėte mūsų programą!
6 </string>
    <string name="thank_you_for_trying_our_app">50% greičiau. Visos savybės. Nėra skelbimų</string>
    <string name="_50_cheaper_all_features_no_ads">50% greičiau. Visos savybės. Nėra skelbimų</string>
    <string name="please_exclude_our_app_from_being_stopped_by_your_system">50% greičiau. Visos savybės. Nėra skelbimų</string> 


Thanks

**Comment by Ra-Na** [comment]
The delimiter of the second string is broken, its just ":" instead of "::". Also, it may help to remove the blanks. This worked for me:
1::gali sukelti programų netinkamą veikimą. Norėdami to išvengti, pasirinkite ir apsaugokite mūsų programą akumuliatoriaus nustatymuose.
2::Apsaugokite nuo akumuliatoriaus taupymo
3::Dėmesio!
4::Tik nauji vartotojai!
5::Ačiū, kad išbandėte mūsų programą!
6::50% greičiau. Visos savybės. Nėra skelbimų

**Comment by psydj1** [comment]
Oh yes, I haven't noticed that the translation removes a delimiter!
Also removing the spaces makes the line numbers go away

Thanks for your time and for creating this in the first place!
I'm happily donating!

**Comment by psydj1** [comment]
Sorted! Pay attention to spacings around the delimiters!
