### ISSUE TITLE
I can´t translate through gtranslate.py

### ISSUE THREAD

**Issue by panovvitalik** [Ra-Na/GTranslate-strings-xml#24]
I try to run: python gtranslate.py

And it's not working :(

Could you please help me?

`D:\Projects\Android\GTranslate-strings-xml-master\GoogleTranslate>python gtranslate.py                                                                                                                                               Enter input filename: [default: strings.xml]

Enter source language: [default: en]

Enter output language(s): (space separated)

ru
=================================================

Traceback (most recent call last):
  File "gtranslate.py", line 240, in <module>
    tree = ET.parse(INFILE)
  File "C:\Users\Vitaly\AppData\Local\Programs\Python\Python38\lib\xml\etree\ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "C:\Users\Vitaly\AppData\Local\Programs\Python\Python38\lib\xml\etree\ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: undefined entity: line 3, column 174`

**Comment by Ra-Na** [comment]
Can you please provide the offending strings.xml file? 
My guess is that it contains html tags that mess with the xml parsing.

**Comment by panovvitalik** [comment]
You are right - xml file contains something that cause crash

Crashed strings.xml:

<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="barcode_app_error_message">Can not run QR barcode scan application\n\n%s\n\nPlease try again or try to install this application manually from Play Market:\n&scanner_qr_bot_link;</string>
</resources>

If I try to translate simpler xml, like this:
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="example">text text</string>
</resources>

It works properly

**Comment by Ra-Na** [comment]
Just replace the offending tags by unique strings that dont get translated like HTMLOPENINGTAG, have the translation, and restore the tags than.

**Comment by panovvitalik** [comment]
@Ra-Na 
In this case I can do it - this is only one line file. 
But if I have strings.xml aprox. 650 lines. And I can't understand which line it can not translate :(

**Comment by panovvitalik** [comment]
...If I try to translate such file

I get following error instead string translation:

`html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"> <html DIR="LTR"> <head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta name="viewport" content="initial-scale=1"><title>https://translate.google.com/m?hl=ru&sl=en&q=Removing+all+messages</title></head> <body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById(\'captcha\');if(e){e.focus();}"> <div style="max-width:400px;"> <hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br> <form id="captcha-form" action="index" method="post"> <script src="https://www.google.com/recaptcha/api.js" async defer></script> <script>var submitCallback = function(response) {document.getElementById(\'captcha-form\').submit();};</script> <div id="recaptcha" class="g-recaptcha" data-sitekey="6LfwuyUTAAAAAOAmoS0fdqijC2PbbdH4kjq62Y1b" data-callback="submitCallback" data-s="yKYGrGTy44j_2GZW6ewMIocCcyDS5jE74dRsvzapxZjukPazXEwUwV9TkFy6NI84lMDHGz7GX8giWlgQbk6nj1k0lBlRsxsVtJDnv6SrNdBWEAXEe8C-DvCmElQ6Y8Hqfl_IHLDICoRbm-7rnYRaesJ56QdmvdOBb5o-H-OK7I5eBcPzUXfSI8b97WnpIUOWMEve7Syr09nWBK7FQ8RXbCjS99x-UPN6SMq-PvoLUchWhLXJo80i3ac"></div> <input type=\'hidden\' name=\'q\' value=\'EgS5DXCbGJ_d5fgFIhkA8aeDS6eLA1Cent_A2gnyKgrgzRQ1-hUnMgFy\'><input type="hidden" name="continue" value="https://translate.google.com/m?hl=ru&sl=en&q=Removing+all+messages"> </form> <hr noshade size="1" style="color:#ccc; background-color:#ccc;"> <div style="font-size:13px;"> <b>ÐÐ± ÑÑÐ¾Ð¹ ÑÑÑÐ°Ð½Ð¸ÑÐµ</b><br><br> ÐÑ Ð·Ð°ÑÐµÐ³Ð¸ÑÑÑÐ¸ÑÐ¾Ð²Ð°Ð»Ð¸ Ð¿Ð¾Ð´Ð¾Ð·ÑÐ¸ÑÐµÐ»ÑÐ½ÑÐ¹ ÑÑÐ°ÑÐ¸Ðº, Ð¸ÑÑÐ¾Ð´ÑÑÐ¸Ð¹ Ð¸Ð· Ð²Ð°ÑÐµÐ¹ ÑÐµÑÐ¸. Ð¡ Ð¿Ð¾Ð¼Ð¾ÑÑÑ ÑÑÐ¾Ð¹ ÑÑÑÐ°Ð½Ð¸ÑÑ Ð¼Ñ ÑÐ¼Ð¾Ð¶ÐµÐ¼ Ð¾Ð¿ÑÐµÐ´ÐµÐ»Ð¸ÑÑ, ÑÑÐ¾ Ð·Ð°Ð¿ÑÐ¾ÑÑ Ð¾ÑÐ¿ÑÐ°Ð²Ð»ÑÐµÑÐµ Ð¸Ð¼ÐµÐ½Ð½Ð¾ Ð²Ñ, Ð° Ð½Ðµ ÑÐ¾Ð±Ð¾Ñ. <a href="#" onclick="document.getElementById(\'infoDiv\').style.display=\'block\';">ÐÐ¾ÑÐµÐ¼Ñ ÑÑÐ¾ Ð¼Ð¾Ð³Ð»Ð¾ Ð¿ÑÐ¾Ð¸Ð·Ð¾Ð¹ÑÐ¸?</a><br><br> <div id="infoDiv" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;"> Ð­ÑÐ° ÑÑÑÐ°Ð½Ð¸ÑÐ° Ð¾ÑÐ¾Ð±ÑÐ°Ð¶Ð°ÐµÑÑÑ Ð² ÑÐµÑ ÑÐ»ÑÑÐ°ÑÑ, ÐºÐ¾Ð³Ð´Ð° Ð°Ð²ÑÐ¾Ð¼Ð°ÑÐ¸ÑÐµÑÐºÐ¸Ð¼Ð¸ ÑÐ¸ÑÑÐµÐ¼Ð°Ð¼Ð¸ Google ÑÐµÐ³Ð¸ÑÑÑÐ¸ÑÑÑÑÑÑ Ð¸ÑÑÐ¾Ð´ÑÑÐ¸Ðµ Ð¸Ð· Ð²Ð°ÑÐµÐ¹ ÑÐµÑÐ¸ Ð·Ð°Ð¿ÑÐ¾ÑÑ, ÐºÐ¾ÑÐ¾ÑÑÐµ Ð½Ð°ÑÑÑÐ°ÑÑ <a href="//www.google.ru/policies/terms/">Ð£ÑÐ»Ð¾Ð²Ð¸Ñ Ð¸ÑÐ¿Ð¾Ð»ÑÐ·Ð¾Ð²Ð°Ð½Ð¸Ñ</a>. Ð¡ÑÑÐ°Ð½Ð¸ÑÐ° Ð¿ÐµÑÐµÑÑÐ°Ð½ÐµÑ Ð¾ÑÐ¾Ð±ÑÐ°Ð¶Ð°ÑÑÑÑ Ð¿Ð¾ÑÐ»Ðµ ÑÐ¾Ð³Ð¾, ÐºÐ°Ðº ÑÑÐ¸ Ð·Ð°Ð¿ÑÐ¾ÑÑ Ð¿ÑÐµÐºÑÐ°ÑÑÑÑÑ. ÐÐ¾ ÑÑÐ¾Ð³Ð¾ Ð¼Ð¾Ð¼ÐµÐ½ÑÐ° Ð´Ð»Ñ Ð¸ÑÐ¿Ð¾Ð»ÑÐ·Ð¾Ð²Ð°Ð½Ð¸Ñ ÑÐ»ÑÐ¶Ð± Google Ð½ÐµÐ¾Ð±ÑÐ¾Ð´Ð¸Ð¼Ð¾ Ð¿ÑÐ¾ÑÐ¾Ð´Ð¸ÑÑ Ð¿ÑÐ¾Ð²ÐµÑÐºÑ Ð¿Ð¾ ÑÐ»Ð¾Ð²Ñ.<br><br>ÐÑÑÐ¾ÑÐ½Ð¸ÐºÐ¾Ð¼ Ð·Ð°Ð¿ÑÐ¾ÑÐ¾Ð² Ð¼Ð¾Ð¶ÐµÑ ÑÐ»ÑÐ¶Ð¸ÑÑ Ð²ÑÐµÐ´Ð¾Ð½Ð¾ÑÐ½Ð¾Ðµ ÐÐ, Ð¿Ð¾Ð´ÐºÐ»ÑÑÐ°ÐµÐ¼ÑÐµ Ð¼Ð¾Ð´ÑÐ»Ð¸ Ð±ÑÐ°ÑÐ·ÐµÑÐ° Ð¸Ð»Ð¸ ÑÐºÑÐ¸Ð¿Ñ, Ð½Ð°ÑÑÑÐ¾ÐµÐ½Ð½ÑÐ¹ Ð½Ð° Ð°Ð²ÑÐ¾Ð¼Ð°ÑÐ¸ÑÐµÑÐºÐ¸Ñ ÑÐ°ÑÑÑÐ»ÐºÑ Ð·Ð°Ð¿ÑÐ¾ÑÐ¾Ð². ÐÑÐ»Ð¸ Ð²Ñ Ð¸ÑÐ¿Ð¾Ð»ÑÐ·ÑÐµÑÐµ Ð¾Ð±ÑÐ¸Ð¹ Ð´Ð¾ÑÑÑÐ¿ Ð² ÐÐ½ÑÐµÑÐ½ÐµÑ, Ð¿ÑÐ¾Ð±Ð»ÐµÐ¼Ð° Ð¼Ð¾Ð¶ÐµÑ Ð±ÑÑÑ Ñ ÐºÐ¾Ð¼Ð¿ÑÑÑÐµÑÐ¾Ð¼ Ñ ÑÐ°ÐºÐ¸Ð¼ Ð¶Ðµ IP-Ð°Ð´ÑÐµÑÐ¾Ð¼, ÐºÐ°Ðº Ñ Ð²Ð°Ñ. ÐÐ±ÑÐ°ÑÐ¸ÑÐµÑÑ Ðº ÑÐ²Ð¾ÐµÐ¼Ñ ÑÐ¸ÑÑÐµÐ¼Ð½Ð¾Ð¼Ñ Ð°Ð´Ð¼Ð¸Ð½Ð¸ÑÑÑÐ°ÑÐ¾ÑÑ. <a href="//support.google.com/websearch/answer/86640">ÐÐ¾Ð´ÑÐ¾Ð±Ð½ÐµÐµ...</a><br><br>ÐÑÐ¾Ð²ÐµÑÐºÐ° Ð¿Ð¾ ÑÐ»Ð¾Ð²Ñ Ð¼Ð¾Ð¶ÐµÑ ÑÐ°ÐºÐ¶Ðµ Ð¿Ð¾ÑÐ²Ð»ÑÑÑÑÑ, ÐµÑÐ»Ð¸ Ð²Ñ Ð²Ð²Ð¾Ð´Ð¸ÑÐµ ÑÐ»Ð¾Ð¶Ð½ÑÐµ Ð·Ð°Ð¿ÑÐ¾ÑÑ, Ð¾Ð±ÑÑÐ½Ð¾ ÑÐ°ÑÐ¿ÑÐ¾ÑÑÑÐ°Ð½ÑÐµÐ¼ÑÐµ Ð°Ð²ÑÐ¾Ð¼Ð°ÑÐ¸Ð·Ð¸ÑÐ¾Ð²Ð°Ð½Ð½ÑÐ¼Ð¸ ÑÐ¸ÑÑÐµÐ¼Ð°Ð¼Ð¸, Ð¸Ð»Ð¸ Ð¶Ðµ Ð²Ð²Ð¾Ð´Ð¸ÑÐµ Ð·Ð°Ð¿ÑÐ¾ÑÑ Ð¾ÑÐµÐ½Ñ ÑÐ°ÑÑÐ¾. </div><br> IP-Ð°Ð´ÑÐµÑ: 185.13.112.155<br>ÐÑÐµÐ¼Ñ: 2020-07-23T11:03:59Z<br>URL: https://translate.google.com/m?hl=ru&sl=en&q=Removing+all+messages<br> </div></div> </body> </html>`

**Comment by Ra-Na** [comment]
This means that you have made too many requests to the google server: Just search for "recaptcha" in the answer string. A captcha is returned to you instead of the translation. Wait for a day or so, then you are not blocked anymore.

**Comment by panovvitalik** [comment]
This error occured at first run of my work string.xml file. I can wait a day ok - but when I run again, I suppose I will recieve the same error :-)
Ok, I understand. Thanks

**Comment by Ra-Na** [comment]
I recommend to simply use the copy-paste variant that works on the web page. It does not have the captcha problem and you can use better translation services than google translate.

**Comment by panovvitalik** [comment]
In this case there is a lot of manual work.
Ok I will try. Thank you
