### ISSUE TITLE
EN -> TH Translation  Error

### ISSUE THREAD

**Issue by mahirozdin** [Ra-Na/GTranslate-strings-xml#5]
TH letters are broken comes like ??????? ?? ? ? ???? 

http://prntscr.com/kb9vac

**Comment by Ra-Na** [comment]
Did you check whether your system has the Thai font installed?Am 26.07.2018 1:55 nachm. schrieb Mahir Taha Özdin <notifications@github.com>:TH letters are broken comes like ??????? ?? ? ? ????
http://prntscr.com/kb9vac

**Comment by mahirozdin** [comment]
Yes I did. I found a solution
LINE 175 
` if r.encoding is None or r.encoding == 'ISO-8859-1':`
Change TO
` if r.encoding is None or r.encoding == 'windows-874':`

It's working for Thai but might broke other languages idk yet.

**Comment by mahirozdin** [comment]
Could you please contact with me about future of the project. ozdinmt@gmai.com

**Comment by Ra-Na** [comment]
That was a really good comment. Actually, we should read the encoding from r.content or r.text, set it correctly, and then pull r.text to post-process it. I will fix this issue soon. I did not expect that the encoding is different when using different target languages, but that is what actually happens. TH ->windows-874, DE->ISO-8859-1
