### ISSUE TITLE
French translations are not escaped

### ISSUE THREAD

**Issue by radixdev** [Ra-Na/GTranslate-strings-xml#7]
Input:
```
<resources>
    <string name="how_does_it_work_slide_description">First, enable the assistant with the play button then start playing the trivia app.</string>
</resources>
```

Output:
```
    <string name="how_does_it_work_slide_description">Tout d'abord, activez l'assistant avec le bouton de lecture, puis lancez la lecture de l'application.</string>
```

The apostrophes need to be escaped to be valid according to Android Studio.

**Comment by jpvs0101** [comment]
Yes, I also face this issue!

On Saturday, September 15, 2018, Julian Richard Contreras <
notifications@github.com> wrote:
> Input:
>
> <resources>
> <string name="how_does_it_work_slide_description">First, enable the
assistant with the play button then start playing the trivia app.</string>
> </resources>
>
> Output:
>
> <string name="how_does_it_work_slide_description">Tout d'abord, activez
l'assistant avec le bouton de lecture, puis lancez la lecture de
l'application.</string>
>
> The apostrophes need to be escaped to be valid according to Android
Studio,
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci5.googleusercontent.com/proxy/G8S3f36qIX-riYnwiQQRQBR3j2bxdEXoeh66Xa4HLittO0A0OwdsoAJqWNwWcPoD65gzPokXyb_K-kbWYcQoKDuRZPGngFXrqBhs9k0R7I6IyX_rpgSKPpkPkMSLvwA64uBUfvDU5ntTXX5UA2tEAo77PtI9kg=s0-d-e1-ft#https://github.com/notifications/beacon/AkhD6js37gyQ2UKZNigLqUUnVLm6GO7Zks5ubHeegaJpZM4WqLcx.gif>

**Comment by lintax** [comment]
Yes, same with Italian and some other languages as well.

**Comment by sblandford** [comment]
Change line 213 of gtranslate.py from
`return html.unescape(parsed2)`
to
`html.unescape(parsed2).replace("'", r"\'")`

**Comment by Ra-Na** [comment]
Thanks!

**Comment by radixdev** [comment]
gg
