### ISSUE TITLE
File result - is corrupted

### ISSUE THREAD

**Issue by ofirkris** [Ra-Na/GTranslate-strings-xml#8]
Service has stopped operating, it outputs a corrupted file.

**Comment by Ra-Na** [comment]
can you please elaborate?

**Comment by ofirkris** [comment]
a week ago the service still worked as expected at - https://asrt.gluege.boerde.de/ - 
if you try it now, and check the output file, you will notice it's corrupted and not usable.

**Comment by Ra-Na** [comment]
I cannot reproduce this problem. Just tried it, worked as it should. Can you please check again and be more specific about the corruption? Also, it may be helpful if you provide your input xml or check with a simpler input.

**Comment by mahirozdin** [comment]
@ofirkris  can you share the strings.xml file with me

**Comment by Ra-Na** [comment]
Here, these are in- and output files:
[in-and-out.zip.zip](https://github.com/Ra-Na/GTranslate-strings-xml/files/2879192/in-and-out.zip.zip)
