### ISSUE TITLE
Request php code

### ISSUE THREAD

**Issue by fadlyfdl** [Ra-Na/GTranslate-strings-xml#9]
Request php code
https://asrt.gluege.boerde.de/index.php
https://asrt.gluege.boerde.de/run.php
https://asrt.gluege.boerde.de/run2.php

**Comment by Ra-Na** [comment]
Dear fadlyfdl,

I have not disclosed the php files because I fear to be pwnd. I am not a web developer, so it may have more security holes than usual.

Regards,

Ra-Na

**Comment by fadlyfdl** [comment]
Can you share? I will only run it on the local network.
I use it to translate ROM Miui.
thank you
Telegram @fadlyfdl

**Comment by mahirozdin** [comment]
@fadlyfdl  not that hard to trigger python code from php...
